services:

  Tejadong_graphql_mutation_validator.validator:
    class: Tejadong\GraphQLMutationValidatorBundle\Validator\MutationValidator
    public: true
    arguments:
      - "@validator"

  Tejadong\GraphQLMutationValidatorBundle\Validator\MutationValidator:
    alias: Tejadong_graphql_mutation_validator.validator

  Tejadong_graphql_mutation_validator.formatter:
    class: Tejadong\GraphQLMutationValidatorBundle\Formatter\Formatter
    public: false
    tags:
      - { name: kernel.event_listener, event: graphql.error_formatting, method: onErrorFormatting }